# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  serializer:
    serialize_null: true
    groups: [Default]
  body_listener: true
  param_fetcher_listener: true
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  format_listener:
    rules:
      - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }